# Generated by Django 4.1.4 on 2023-01-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creacio',
            new_name='Creacion',
        ),
    ]
