# Generated by Django 4.1.4 on 2023-02-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_creacion_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creacion',
            name='product_image',
        ),
    ]
