# Generated by Django 4.1.4 on 2023-01-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_rename_creacio_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacion',
            name='modelo',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
