# Generated by Django 4.1.4 on 2023-01-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_creacion_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Type of clothes',
                'verbose_name_plural': 'Type of clothes',
                'db_table': 'Type_of_clothing',
            },
        ),
        migrations.RemoveField(
            model_name='creacion',
            name='modelo',
        ),
    ]
