# Generated by Django 4.1.4 on 2023-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_remove_creacion_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
