# Generated by Django 4.1.4 on 2023-02-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0004_creacion_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creacion',
            old_name='image',
            new_name='product_picture',
        ),
    ]
