# Generated by Django 4.1.4 on 2023-01-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_orden_alter_pago_options_alter_pago_table_and_more'),
        ('aplicacion1', '0004_type_clothing_remove_creacion_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type_Clothing',
        ),
    ]
