# Generated by Django 4.1.4 on 2023-02-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_delete_pagoo_remove_ordeness_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordeness',
            name='Email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
