# Generated by Django 4.1.4 on 2023-02-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ordeness_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeness',
            name='Email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
