# Generated by Django 4.1.4 on 2023-02-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_ordeness_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordeness',
        ),
    ]
