# Generated by Django 4.1.4 on 2023-01-11 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacion1', '0004_type_clothing_remove_creacion_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
                'db_table': 'Payment_method',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Cliente')),
                ('clothes_name', models.CharField(max_length=100, verbose_name='Prenda')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creacion de la orden')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.type_clothing', verbose_name='Categoria de la prenda')),
                ('payment', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.payment', verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'db_table': 'Sales',
            },
        ),
    ]
