# Generated by Django 4.1.4 on 2023-01-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creacion de la orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pago',
                'db_table': 'Pago',
            },
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'PAGO', 'verbose_name_plural': 'PAGO'},
        ),
        migrations.AlterModelTable(
            name='pago',
            table='metodo_de_pago',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='Pago',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.AddField(
            model_name='orden',
            name='Pago',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pago', verbose_name='Metodo de pago'),
        ),
    ]
